### ISSUE TITLE
numpy.distutils deprecated as of python 3.12

### ISSUE THREAD

**Issue by shaunlowis** [sonofeft/RocketCEA#37]
Posting this for visibility, obviously a "solution" is to use a python version earlier than 3.12. However, this will also be [removed from versions earlier than 3.12 in Oct, 2025](https://numpy.org/doc/stable/reference/distutils_status_migration.html#distutils-status-migration), so needs to be addressed at some point.

With the newest python release, numpy now no longer includes distutils, see [here](https://numpy.org/doc/stable/reference/distutils.html). This results in the following error when trying the usual `python -m pip install rocketcea`:

```
Collecting rocketcea
  Using cached rocketcea-1.1.34.tar.gz (38.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8wg81_vj/rocketcea_cc4566460e524c06aa5b992ef789e0b7/setup.py", line 21, in <module>
          from numpy.distutils.core import Extension, setup
      ModuleNotFoundError: No module named 'numpy.distutils'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

As for a solution to this problem, it seems that [moving to setuptools](https://numpy.org/doc/stable/reference/distutils_status_migration.html#moving-to-setuptools) may be easiest.

**Comment by sonofeft** [comment]
Thanks for the suggestion. Clearly I need to get that done.

**Comment by a-detiste** [comment]
I can't find the tarballs for the releases

**Comment by a-detiste** [comment]
python3-future is broken on  Python3.12 ...

**Comment by a-detiste** [comment]
I tried it, plain setuptools is not the solution.

```
To assess that, there are the numpy.distutils features that are not present in setuptools:

Fortran build support <--------------------
```

**Comment by stellarLines** [comment]
Even with Python 3.9.11 and numpy 1.22.4, I encounter this error.
```
Collecting rocketcea
  Using cached rocketcea-1.1.34.tar.gz (38.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\<username>\AppData\Local\Temp\pip-build-env-oewskvlh\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\<username>\AppData\Local\Temp\pip-build-env-oewskvlh\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\<username>\AppData\Local\Temp\pip-build-env-oewskvlh\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\<username>\AppData\Local\Temp\pip-build-env-oewskvlh\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 21, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by sonofeft** [comment]
Are you sure you have numpy installed?
The error message says "ModuleNotFoundError: No module named 'numpy'"

**Comment by stellarLines** [comment]
```
pip list
Package              Version
-------------------- ----------
ansi2html            1.9.1
blinker              1.7.0
build                1.0.3
CacheControl         0.13.1
certifi              2023.11.17
charset-normalizer   3.3.2
cleo                 2.1.0
colorama             0.4.6
contourpy            1.2.0
crashtest            0.4.1
cycler               0.12.1
dash-core-components 2.0.0
dash-html-components 2.0.0
dash-table           5.0.0
distlib              0.3.8
dulwich              0.21.7
fastjsonschema       2.19.1
filelock             3.13.1
fonttools            4.47.2
idna                 3.6
importlib-metadata   7.0.1
importlib-resources  6.1.1
install              1.3.5
installer            0.7.0
itsdangerous         2.1.2
jaraco.classes       3.3.0
keyring              24.3.0
kiwisolver           1.4.5
MarkupSafe           2.1.4
matplotlib           3.8.2
more-itertools       10.2.0
msgpack              1.0.7
nest-asyncio         1.6.0
numpy                1.22.4
packaging            23.2
pexpect              4.9.0
pillow               10.2.0
pip                  23.3.2
pkginfo              1.9.6
platformdirs         3.11.0
plotly               5.18.0
poetry               1.7.1
poetry-core          1.8.1
poetry-plugin-export 1.6.0
ptyprocess           0.7.0
pygame               2.5.2
pyglet               2.0.10
pyparsing            3.1.1
pyproject_hooks      1.0.0
python-dateutil      2.8.2
pytz                 2023.4
pywin32-ctypes       0.2.2
rapidfuzz            3.6.1
requests             2.31.0
requests-toolbelt    1.0.0
retrying             1.3.4
setuptools           58.1.0
shellingham          1.5.4
six                  1.16.0
tenacity             8.2.3
tomli                2.0.1
tomlkit              0.12.3
trove-classifiers    2024.1.8
typing_extensions    4.9.0
tzdata               2023.4
urllib3              2.2.0
virtualenv           20.25.0
Werkzeug             3.0.1
wxPython             4.2.1
zipp                 3.17.0
```

**Comment by sonofeft** [comment]
Are you using a virtual environment in which numpy is not installed?
For whatever reason on your local computer, numpy is not being found.
That does not sound like a rocketCEA issue, but a local setup issue.

**Comment by stellarLines** [comment]
I have tried installing to a virtual environment. I've tried installing to the local user environment. I even tried using Poetry. RocketCEA is the only package I'm not able to install.

**Comment by sonofeft** [comment]
Installing on Windows can be tricky.
I recommend you look at the docs at: https://rocketcea.readthedocs.io/en/latest/quickstart.html

After you read the docs, if you are still having trouble, I would need to see more details of what commands you are entering and what error messages you are getting.

**Comment by stellarLines** [comment]
I was able to get it up and running on WSL. I was hoping to keep it all native on Windows since I want to pass data between a custom python module that uses RocketCEA and other 3rd-party tools that run natively on Windows, but with WSLg on Windows 11, this shouldn't be a problem. Thanks for the help.

**Comment by sonofeft** [comment]
The Windows instructions for the last version of RocketCEA to use numpy.distutils are posted at https://rocketcea.readthedocs.io/en/latest/quickstart.html#link-windows-bat-file
You will likely require either a virtual environment or a dedicated python install with old versions of pip and numpy.

WSL is also a good option (see: https://rocketcea.readthedocs.io/en/latest/quickstart.html#windows-10-or-11-with-wsl)

As I transition to meson (https://mesonbuild.com/), hopefully the install process will become much more simple and will add support for python version 3.12 and above.
