### ISSUE TITLE
Unable to install RocketCEA, Ubuntu

### ISSUE THREAD

**Issue by shaunlowis** [sonofeft/RocketCEA#46]
Apologies, it is me again. I've been setting up a new linux computer with RocketCEA and just can't seem to get an install working.
For Ubuntu 22.04.4, 24.04, I tried fresh installs;
```
sudo apt update && upgrade
sudo apt install gfortran

# now for python:
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get install python3.11-venv

# make a virtual environment and activate it
python3.11 -m venv .venv
source .venv/bin/activate
```

I've also tried Python 3.10, 3.12, but get similar errors. Install procedure used:

```
# with .venv active:
python -m pip install --no-cache-dir numpy
python -m pip install --no-cache-dir scipy
# below line gets rocketcea==1.2.0
python -m pip install --no-cache-dir rocketcea
```

For RocketCEA 1.2.0 I get a `metedata-generation-failed` error (same error with and without the `--prefer-binary` flag):
```
$ python -m pip install --no-cache-dir --prefer-binary rocketcea==1.2.0
Collecting rocketcea==1.2.0
  Downloading rocketcea-1.2.0.tar.gz (70.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.1/70.1 MB 4.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      + meson setup /tmp/pip-install-stqj0oab/rocketcea_306ec733ebc3470ca1e79d5442c7bc6f /tmp/pip-install-stqj0oab/rocketcea_306ec733ebc3470ca1e79d5442c7bc6f/.mesonpy-iom_fzhb -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-stqj0oab/rocketcea_306ec733ebc3470ca1e79d5442c7bc6f/.mesonpy-iom_fzhb/meson-python-native-file.ini
      The Meson build system
      Version: 1.4.1
      Source dir: /tmp/pip-install-stqj0oab/rocketcea_306ec733ebc3470ca1e79d5442c7bc6f
      Build dir: /tmp/pip-install-stqj0oab/rocketcea_306ec733ebc3470ca1e79d5442c7bc6f/.mesonpy-iom_fzhb
      Build type: native build
      Project name: rocketcea
      Project version: undefined
      C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
      C linker for the host machine: cc ld.bfd 2.38
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      ../meson.build:5: WARNING: add_languages is missing native:, assuming languages are wanted for both host and build.
      Fortran compiler for the host machine: gfortran (gcc 11.4.0 "GNU Fortran (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
      Fortran linker for the host machine: gfortran ld.bfd 2.38
      Program python found: YES (/home/thruster-testing/code/star_forge/.venv/bin/python)
      Did not find pkg-config by name 'pkg-config'
      Found pkg-config: NO
      Run-time dependency python found: NO (tried pkgconfig, pkgconfig and sysconfig)
      
      ../meson.build:9:12: ERROR: Python dependency not found
      
      A full log can be found at /tmp/pip-install-stqj0oab/rocketcea_306ec733ebc3470ca1e79d5442c7bc6f/.mesonpy-iom_fzhb/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

$ python -m pip list
Package    Version
---------- -------
numpy      1.26.4
pip        24.0
pkgconfig  1.5.5
scipy      1.13.1
setuptools 65.5.0
```
I tried to get the output of the meson-log.txt mentioned above, but got this:

```
$ cat /tmp/pip-install-ku7_yu5s/rocketcea_58ee29b7b754404faece625638d1edf5/.mesonpy-6kpar0ib/meson-logs/meson-log.txt
cat: /tmp/pip-install-ku7_yu5s/rocketcea_58ee29b7b754404faece625638d1edf5/.mesonpy-6kpar0ib/meson-logs/meson-log.txt: No such file or directory
```

For RocketCEA 1.1.34 I get a `ModuleNotFoundError` (same error with and without the `--prefer-binary` flag):

```
$ python -m pip install --no-cache-dir --prefer-binary rocketcea==1.1.34
Collecting rocketcea==1.1.34
  Downloading rocketcea-1.1.34.tar.gz (38.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.5/38.5 MB 9.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/thruster-testing/code/star_forge/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/thruster-testing/code/star_forge/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/thruster-testing/code/star_forge/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-xkw9ckog/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-xkw9ckog/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-xkw9ckog/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-xkw9ckog/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 21, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

$ python -m pip list
Package    Version
---------- -------
numpy      1.26.4
pip        24.0
pkgconfig  1.5.5
scipy      1.13.1
setuptools 65.5.0
```

I am a bit stumped as to how to get around this, as I recently tested the exact above setup, on a different computer, with no issues.
Kind of ran out of time for further testing on this today, but might see if it is something hardware related and test on another laptop.

It seems that rocketcea is having trouble finding dependencies, but I have no issues installing all of my other required packages.

**Comment by shaunlowis** [comment]
Tested install on different laptop with Ubuntu 24.04, same issues as above: 

I have a working install on my laptop:
OS: Ubuntu 22.04.4 LTS
Python: 3.11.9 (installed with deadsnakes ppa, 3.11-venv)

Other computer, fresh python install:
OS: Ubuntu 24.04
Python: 3.11.9 (installed with deadsnakes ppa, 3.11-venv)

Get exactly the same errors above with RocketCEA 1.2.0 and 1.3.4

It doesn't look like there has been a new 3.11 release on the PPA since April 28th:
https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa

Has there been some change to the PyPI release?

**Comment by sonofeft** [comment]
I ran Ubuntu 24.04 on VirtualBox and used the following steps to successfully install RocketCEA

sudo apt update && upgrade
sudo apt install python3 python3-pip ipython3

sudo apt-get install gfortran
python3 --version

#  make virtual environment
sudo apt install python3.12-venv
python3 -m venv ~/Public/RocketCEA

cd ~/Public/RocketCEA
source ./bin/activate

pip3 install rocketcea

# test installation
python3 -c "from rocketcea.cea_obj import CEA_Obj; C=CEA_Obj(oxName='LOX', fuelName='LH2'); print(C.get_Isp())"
374.30361765576896
